# Generated by Django 6.1.1 on 2026-09-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_note',
            field=models.CharField(blank=True, help_text="e.g. 'Busy until 3pm', 'On a job'", max_length=100),
        ),
    ]
