# Generated by Django 6.1.1 on 2026-09-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_provider_reply_review_provider_reply_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status_note',
        ),
    ]
